#!/usr/bin/env sh
# One-shot self-test for this docc skill: confirm the compiler runs here and
# that a bundled example builds to a .docx.
#
# Generated by `docc profile package`. Run it from the skill's directory.

set -eu

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$DIR"

echo "== docc skill probe =="
echo "uname -s : $(uname -s 2>/dev/null || echo '?')"
echo "uname -m : $(uname -m 2>/dev/null || echo '?')"

BIN="bin/docc-linux-amd64"
if [ ! -f "$BIN" ]; then
  echo "PROBE RESULT: FAIL — bundled binary $BIN is missing from the skill."; exit 3
fi
# Packaging may strip the exec bit; restore it.
chmod +x "$BIN" 2>/dev/null || true
DOCC="./$BIN"

if ! VER=$("$DOCC" version 2>&1); then
  echo "----- output -----"; echo "$VER"; echo "------------------"
  echo "PROBE RESULT: FAIL — this environment refused to execute the bundled binary."
  exit 1
fi
echo "docc     : $VER"

EX="examples/ch_legal.md"
OUT="$DIR/probe-out.docx"

echo "-- check $EX --"
"$DOCC" check --schema-dir config/schemas "$EX"
echo "-- build $EX --"
"$DOCC" build --schema-dir config/schemas --theme-dir config/themes --output "$OUT" "$EX"

if [ -s "$OUT" ]; then
  echo "wrote    : $OUT ($(wc -c < "$OUT") bytes)"
  echo "PROBE RESULT: PASS — the compiler runs here and produced a .docx."
else
  echo "PROBE RESULT: FAIL — build reported success but wrote no .docx."
  exit 2
fi
