package ingest

import (
	"strings"
	"testing"
)

func TestAssembleBannerAndFrontmatter(t *testing.T) {
	pages := []PageResult{
		{Index: 1, Markdown: "# Klage"},
		{Index: 2, Markdown: "Erste Erwägung."},
	}
	got := Assemble(pages, AssembleOptions{SourceFile: "klage.pdf", DocType: "legal"})

	if got == "" {
		t.Fatal("Assemble returned an empty document")
	}
	want := []string{
		"---\n",
		"document_type: legal\n",
		"generated by `docc ingest` from klage.pdf",
		"# Klage",
		"Erste Erwägung.",
	}
	for _, w := range want {
		if !strings.Contains(got, w) {
			t.Errorf("assembled document missing %q\n---\n%s", w, got)
		}
	}
}

func TestAssembleFlagsLowConfidencePages(t *testing.T) {
	pages := []PageResult{
		{Index: 1, Markdown: "fine"},
		{Index: 2, Markdown: "shaky", LowConfidence: true, Note: "no text layer found on this page — verify carefully"},
		{Index: 3, Markdown: "cut off", LowConfidence: true, Note: "response was cut off at max_tokens — page is likely incomplete"},
	}
	got := Assemble(pages, AssembleOptions{SourceFile: "scan.pdf"})

	if !strings.Contains(got, "page 2: low confidence — no text layer found on this page — verify carefully") {
		t.Errorf("expected a low-confidence banner line for page 2 with its reason, got:\n%s", got)
	}
	if !strings.Contains(got, "page 3: low confidence — response was cut off at max_tokens — page is likely incomplete") {
		t.Errorf("expected a low-confidence banner line for page 3 with its reason, got:\n%s", got)
	}
}

func TestAssembleNoLowConfidenceBanner(t *testing.T) {
	pages := []PageResult{{Index: 1, Markdown: "fine"}}
	got := Assemble(pages, AssembleOptions{SourceFile: "clean.pdf"})

	if strings.Contains(got, "low-confidence") {
		t.Errorf("did not expect a low-confidence banner, got:\n%s", got)
	}
}

func TestAssembleOmitsDocTypeWhenEmpty(t *testing.T) {
	pages := []PageResult{{Index: 1, Markdown: "text"}}
	got := Assemble(pages, AssembleOptions{SourceFile: "x.pdf"})

	if strings.Contains(got, "document_type:") {
		t.Errorf("did not expect a document_type line when DocType is empty, got:\n%s", got)
	}
}
