package ingest

import (
	"fmt"
	"strings"
	"time"
)

// AssembleOptions configures document assembly.
type AssembleOptions struct {
	// SourceFile is the original PDF/image path, recorded in the banner.
	SourceFile string
	// DocType, if non-empty, is written into the frontmatter's document_type
	// field so the draft can be checked without an extra --type flag.
	DocType string
}

// Assemble stitches per-page markdown into one document, prefixed with
// generic frontmatter and a banner marking it as machine-generated.
//
// Frontmatter stays generic — a title placeholder and document_type only —
// rather than schema-aware: filling schema-specific fields (parties, case
// references, ...) reliably needs schema knowledge this package deliberately
// does not have. docc check already reports whatever is missing once the
// author fills the rest in by hand, which is the point: nothing ingest
// produces is auto-trusted.
func Assemble(pages []PageResult, opts AssembleOptions) string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("docc: 1\n")
	if opts.DocType != "" {
		fmt.Fprintf(&b, "document_type: %s\n", opts.DocType)
	}
	b.WriteString("title: \"\"\n")
	b.WriteString("---\n\n")

	fmt.Fprintf(&b, "<!-- generated by `docc ingest` from %s on %s — review before treating this as a source document -->\n",
		opts.SourceFile, time.Now().UTC().Format("2006-01-02"))

	for _, p := range pages {
		if p.LowConfidence {
			fmt.Fprintf(&b, "<!-- page %d: low confidence — %s -->\n", p.Index, p.Note)
		}
	}
	b.WriteString("\n")

	for i, p := range pages {
		if i > 0 {
			b.WriteString("\n\n")
		}
		b.WriteString(p.Markdown)
	}
	b.WriteString("\n")
	return b.String()
}
