package ingest

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// AssembleOptions configures document assembly.
type AssembleOptions struct {
	// SourceFile is the original PDF/image path, recorded in the banner.
	SourceFile string
	// DocType, if non-empty, is written into the frontmatter's document_type
	// field so the draft can be checked without an extra --type flag.
	DocType string
	// Incomplete, if set, marks the document as the output of a run that
	// stopped early.
	Incomplete *Incomplete
}

// Incomplete describes a run that stopped before its last page — interrupted,
// or failed on a page.
type Incomplete struct {
	// Completed and Total are page counts for this run, not for the document:
	// under --pages 8-17, Total is 10.
	Completed, Total int
	// NextPage and LastPage are the 1-based document pages bounding what was
	// not converted, which is exactly the range a resuming run should ask for.
	NextPage, LastPage int
	// Reason is why the run stopped, in the imperative of the error that
	// stopped it, or "interrupted".
	Reason string
}

// resumeRange renders the unconverted pages the way --pages accepts them.
func (in *Incomplete) resumeRange() string {
	if in.NextPage >= in.LastPage {
		return strconv.Itoa(in.NextPage)
	}
	return fmt.Sprintf("%d-%d", in.NextPage, in.LastPage)
}

// resumeCommand is the command that converts what this run did not.
//
// It names an explicit --output, because the default output path is derived
// from the input name: resuming without one would write the remaining pages
// over the very file this partial draft was saved to, destroying the pages it
// exists to preserve. The two files are concatenated by hand, which is honest
// about the fact that nothing here merges them.
func (in *Incomplete) resumeCommand(sourceFile string) string {
	base := strings.TrimSuffix(sourceFile, filepath.Ext(sourceFile))
	out := fmt.Sprintf("%s.pages-%s.md", base, in.resumeRange())
	return fmt.Sprintf("docc ingest --pages %s --output %s %s", in.resumeRange(), out, sourceFile)
}

// The markers Assemble writes, as consts because two things depend on the
// exact wording: the banner itself, and the check that decides whether
// overwriting an existing draft destroys anything.
const (
	generatedMarker  = "generated by `docc ingest`"
	incompleteMarker = "INCOMPLETE — docc ingest stopped"
	// pageMarkerPrefix opens the comment that says where a page of the source
	// document begins. A draft is reviewed against the PDF it came from, and
	// without this the reviewer counts pages; with it, a paragraph that looks
	// wrong is one search away from the page it was read off.
	//
	// It survives docc check and disappears at docc build: internal/ir drops
	// HTML blocks rather than emitting them as visible text, so a marker never
	// reaches the .docx. That is what makes it safe to write unconditionally.
	pageMarkerPrefix = "<!-- docc:page "
)

// PageMarker is the comment marking where a source page begins.
func PageMarker(page int) string {
	return fmt.Sprintf("%s%d -->", pageMarkerPrefix, page)
}

// IsPageMarker reports whether a line is one. Passes that read a draft back —
// structuring, and anything later that walks paragraphs — skip these rather
// than treating them as content.
func IsPageMarker(line string) bool {
	return strings.HasPrefix(strings.TrimSpace(line), pageMarkerPrefix)
}

// DraftInfo describes a markdown file ingest is about to write over.
type DraftInfo struct {
	// Generated reports that ingest wrote this file and nobody has taken the
	// banner off — the difference between re-running a conversion, which is
	// routine, and overwriting a document somebody has edited.
	Generated bool
	// Incomplete reports a partial draft. It is generated output, but not
	// reproducible output: it holds the pages of a run that stopped, and a
	// resume converts a *different* page range, so overwriting it loses
	// transcriptions nothing is going to produce again.
	Incomplete bool
}

// InspectDraft reads just enough of path to classify it.
func InspectDraft(path string) (DraftInfo, error) {
	f, err := os.Open(path) //nolint:gosec // path is the caller's own output target
	if err != nil {
		return DraftInfo{}, err
	}
	defer func() { _ = f.Close() }()

	// Both markers sit just after the frontmatter; a few KiB covers them
	// without reading a whole document to answer a yes/no question.
	head := make([]byte, 4<<10)
	n, err := f.Read(head)
	if err != nil && !errors.Is(err, io.EOF) {
		return DraftInfo{}, err
	}
	head = head[:n]
	return DraftInfo{
		Generated:  bytes.Contains(head, []byte(generatedMarker)),
		Incomplete: bytes.Contains(head, []byte(incompleteMarker)),
	}, nil
}

// Assemble stitches per-page markdown into one document, prefixed with
// generic frontmatter and a banner marking it as machine-generated.
//
// Frontmatter stays generic — the docc version and document_type only —
// rather than schema-aware: filling schema-specific fields (parties, case
// references, ...) reliably needs schema knowledge this package deliberately
// does not have. docc check already reports whatever is missing once the
// author fills the rest in by hand, which is the point: nothing ingest
// produces is auto-trusted.
//
// It writes no placeholder fields, because a schema-agnostic producer cannot
// know which are legal: `title` exists in the letter schema and not the legal
// one, so emitting it made every legal draft open with a DOC011 warning about
// ingest's own boilerplate. DOC004 already names the fields an author has to
// supply, with better hints than a blank line could carry.
func Assemble(pages []PageResult, opts AssembleOptions) string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("docc: 1\n")
	if opts.DocType != "" {
		fmt.Fprintf(&b, "document_type: %s\n", opts.DocType)
	}
	b.WriteString("---\n\n")

	fmt.Fprintf(&b, "<!-- %s from %s on %s — review before treating this as a source document -->\n",
		generatedMarker, opts.SourceFile, time.Now().UTC().Format("2006-01-02"))

	if in := opts.Incomplete; in != nil {
		fmt.Fprintf(&b, "<!-- %s after %d of %d pages: %s -->\n", incompleteMarker, in.Completed, in.Total, in.Reason)
		fmt.Fprintf(&b, "<!-- convert the rest with: %s -->\n", in.resumeCommand(opts.SourceFile))
		fmt.Fprintf(&b, "<!-- then append that file to this one — resuming does not merge -->\n")
	}

	for _, p := range pages {
		if p.LowConfidence {
			fmt.Fprintf(&b, "<!-- page %d: low confidence — %s -->\n", p.Index, p.Note)
		}
	}
	b.WriteString("\n")

	for i, p := range pages {
		if i > 0 {
			b.WriteString("\n\n")
		}
		fmt.Fprintf(&b, "%s\n\n", PageMarker(p.Index))
		b.WriteString(p.Markdown)
	}
	b.WriteString("\n")

	// Repeated at the end because the reader who scrolls to the bottom of a
	// forty-page draft looking for a section that is not there is not the one
	// who read the header.
	if in := opts.Incomplete; in != nil {
		fmt.Fprintf(&b, "\n<!-- transcription stops here — pages %s were not converted -->\n", in.resumeRange())
	}
	return b.String()
}
