package profile

import (
	"archive/zip"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/kevinzehnder/docc/internal/emit"
	"github.com/kevinzehnder/docc/internal/schema"
	"github.com/kevinzehnder/docc/internal/theme"
)

// SkillOptions describes one packaging run.
type SkillOptions struct {
	// SchemaDir and ThemeDir are the resolved directories to package. They are
	// copied verbatim: a packaged skill renders what the profile renders.
	SchemaDir string
	ThemeDir  string
	// Out is the skill directory to create.
	Out string
	// Name is the skill's identifier. It defaults to the output directory's
	// base name.
	Name string
	// Binary is an optional docc executable to bundle. Without one the skill
	// expects docc on PATH, which keeps the artifact small, architecture
	// neutral, and free of a docc version pinned inside every firm's pack.
	Binary string
	// Notes are Markdown files appended to the generated instructions, in
	// order. They carry the two things the generator cannot know, and they are
	// a list because those two are different halves that both belong: the
	// firm's drafting knowledge, which a pack supplies through `skill.notes:`,
	// and how the host this skill is destined for delivers a file, which
	// `--notes` supplies at packaging time. Everything derived from the
	// profile stays generated.
	Notes []string
	// Description overrides the generated one-line skill description — what an
	// agent reads when deciding whether this skill applies at all.
	Description string
}

// SkillResult reports what a packaging run produced.
type SkillResult struct {
	Dir      string   `json:"dir"`
	Name     string   `json:"name"`
	Types    []string `json:"types"`
	Themes   []string `json:"themes"`
	Examples []string `json:"examples"`
	Binary   string   `json:"binary,omitempty"`
	Zip      string   `json:"zip,omitempty"`
	// Description is the pack's own override, empty when the generated one
	// applies.
	Description string `json:"description,omitempty"`
}

// writeSkillManifest makes the packaged skill a pack in its own right, so
// DOCC_PROFILE=<skill dir> resolves its schemas and themes with no flags.
func writeSkillManifest(dir, name string) error {
	manifest := fmt.Sprintf(
		"# Generated by `docc profile package`. It makes this directory a profile\n"+
			"# pack, so `%s=%s` resolves the schemas and themes below.\n"+
			"format: %d\nid: %s\nname: %s\nschemas: config/schemas\nthemes: config/themes\n",
		EnvProfile, "<this directory>", format, name, name)
	return os.WriteFile(filepath.Join(dir, manifestName), []byte(manifest), 0o600)
}

// PackageSkill writes an AgentSkill directory for a profile's schemas and
// themes. The instructions are generated from the schemas rather than kept
// alongside them, because a hand-written skill file drifts from the types it
// claims to document and nothing catches it.
func PackageSkill(opts SkillOptions) (*SkillResult, error) {
	if opts.Out == "" {
		return nil, fmt.Errorf("skill output directory is required")
	}
	name := opts.Name
	if name == "" {
		name = filepath.Base(filepath.Clean(opts.Out))
	}
	if !idPattern.MatchString(name) {
		return nil, fmt.Errorf("invalid skill name %q: must match %s", name, idPattern)
	}

	schemas, err := schema.Load(opts.SchemaDir)
	if err != nil {
		return nil, err
	}
	themes, err := theme.Load(opts.ThemeDir)
	if err != nil {
		return nil, err
	}
	// Packaging a profile that cannot render is the one failure worth refusing
	// outright: the mistake would otherwise surface inside someone else's VM.
	renderable, err := checkPairs(schemas, themes)
	if err != nil {
		return nil, err
	}
	if len(renderable) == 0 {
		return nil, fmt.Errorf("no document type in %s selects a theme, so the skill could not build anything", opts.SchemaDir)
	}

	if err := os.MkdirAll(opts.Out, 0o750); err != nil {
		return nil, fmt.Errorf("create skill directory: %w", err)
	}
	if err := copyTree(opts.SchemaDir, filepath.Join(opts.Out, "config", "schemas")); err != nil {
		return nil, err
	}
	if err := copyTree(opts.ThemeDir, filepath.Join(opts.Out, "config", "themes")); err != nil {
		return nil, err
	}
	// The skill directory is itself a pack: a manifest naming the two
	// directories it just received. That is what lets every command in the
	// instructions be `docc check document.md` with a DOCC_PROFILE pointing
	// here, instead of repeating --schema-dir and --theme-dir on each one —
	// two flags an agent can forget separately, and does.
	if err := writeSkillManifest(opts.Out, name); err != nil {
		return nil, err
	}

	examples, err := writeExamples(schemas, renderable, filepath.Join(opts.Out, "examples"))
	if err != nil {
		return nil, err
	}

	result := &SkillResult{
		Dir: opts.Out, Name: name, Types: renderable,
		Themes: themes.Names(), Examples: examples, Description: opts.Description,
	}
	if opts.Binary != "" {
		result.Binary, err = copyBinary(opts.Binary, opts.Out)
		if err != nil {
			return nil, err
		}
	}
	var notes []byte
	for _, path := range opts.Notes {
		if path == "" {
			continue
		}
		part, err := os.ReadFile(path) //nolint:gosec // the notes file is named by the caller
		if err != nil {
			return nil, fmt.Errorf("read skill notes: %w", err)
		}
		// A blank line between parts: a heading that follows prose directly is
		// not a heading in Markdown, and these parts arrive from two authors
		// who never see each other's file.
		for len(notes) > 0 && !strings.HasSuffix(string(notes), "\n\n") {
			notes = append(notes, '\n')
		}
		notes = append(notes, part...)
	}
	if err := os.WriteFile(filepath.Join(opts.Out, "SKILL.md"), skillDoc(name, schemas, result, notes), 0o600); err != nil {
		return nil, err
	}
	probe := filepath.Join(opts.Out, "probe.sh")
	if err := os.WriteFile(probe, probeScript(result), 0o600); err != nil {
		return nil, err
	}
	// The probe is meant to be run, not just read.
	if err := os.Chmod(probe, 0o700); err != nil { //nolint:gosec // a self-test script the recipient executes; owner-only exec is the point
		return nil, err
	}
	return result, nil
}

// checkPairs validates every schema against the theme it selects and returns
// the types that can actually be built, in sorted order.
func checkPairs(schemas *schema.Set, themes *theme.Set) ([]string, error) {
	var renderable []string
	for _, typ := range schemas.Types() {
		sc, err := schemas.Get(typ)
		if err != nil {
			return nil, err
		}
		if sc.Theme == "" {
			continue
		}
		th, err := themes.Get(sc.Theme)
		if err != nil {
			return nil, fmt.Errorf("schema %q: %w", sc.Type, err)
		}
		if err := emit.Validate(sc, th); err != nil {
			return nil, fmt.Errorf("schema %q and theme %q: %w", sc.Type, th.Name, err)
		}
		renderable = append(renderable, typ)
	}
	sort.Strings(renderable)
	return renderable, nil
}

// writeExamples materialises each type's declared example document. They come
// from the schemas rather than from a directory of their own, so the shipped
// example of a type cannot fall out of step with the type.
func writeExamples(schemas *schema.Set, types []string, dir string) ([]string, error) {
	var written []string
	for _, typ := range types {
		sc, err := schemas.Get(typ)
		if err != nil {
			return nil, err
		}
		if sc.Example == "" {
			continue
		}
		if len(written) == 0 {
			if err := os.MkdirAll(dir, 0o750); err != nil {
				return nil, fmt.Errorf("create examples directory: %w", err)
			}
		}
		body := sc.Example
		if !strings.HasSuffix(body, "\n") {
			body += "\n"
		}
		name := typ + ".md"
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			return nil, err
		}
		written = append(written, name)
	}
	return written, nil
}

func copyBinary(src, out string) (string, error) {
	info, err := os.Stat(src)
	if err != nil {
		return "", fmt.Errorf("bundled binary: %w", err)
	}
	if info.IsDir() {
		return "", fmt.Errorf("bundled binary %s is a directory", src)
	}
	dir := filepath.Join(out, "bin")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", err
	}
	name := filepath.Base(src)
	if err := copyFile(src, filepath.Join(dir, name), 0o755); err != nil {
		return "", err
	}
	return name, nil
}

// copyTree copies a directory verbatim. Symlinks are refused rather than
// followed: a packaged skill is shipped elsewhere, and a link that resolved on
// the packaging machine is at best broken and at worst a file nobody meant to
// publish.
func copyTree(src, dst string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return fmt.Errorf("read %s: %w", src, err)
	}
	if err := os.MkdirAll(dst, 0o750); err != nil {
		return err
	}
	for _, e := range entries {
		from := filepath.Join(src, e.Name())
		to := filepath.Join(dst, e.Name())
		switch {
		case e.Type()&os.ModeSymlink != 0:
			return fmt.Errorf("%s is a symlink; a packaged skill must contain real files", from)
		case e.IsDir():
			if err := copyTree(from, to); err != nil {
				return err
			}
		case e.Type().IsRegular():
			if err := copyFile(from, to, 0o600); err != nil {
				return err
			}
		default:
			return fmt.Errorf("%s is not a regular file", from)
		}
	}
	return nil
}

func copyFile(src, dst string, mode os.FileMode) error {
	in, err := os.Open(src) //nolint:gosec // src is a listed entry of a selected profile directory
	if err != nil {
		return err
	}
	defer func() { _ = in.Close() }()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode) //nolint:gosec // dst is inside the requested output directory
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	return out.Close()
}

// ZipSkill archives a packaged skill directory with the skill nested at the
// archive root, which is what the skill format requires. Timestamps are fixed
// so the same skill packages to the same bytes.
func ZipSkill(dir, dst string) error {
	base := filepath.Base(filepath.Clean(dir))
	f, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600) //nolint:gosec // dst is the requested archive path
	if err != nil {
		return err
	}
	zw := zip.NewWriter(f)
	err = filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		header := &zip.FileHeader{
			Name:     filepath.ToSlash(filepath.Join(base, rel)),
			Method:   zip.Deflate,
			Modified: time.Date(1980, time.January, 1, 0, 0, 0, 0, time.UTC),
		}
		header.SetMode(info.Mode().Perm())
		w, err := zw.CreateHeader(header)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path) //nolint:gosec // path comes from walking the requested skill directory
		if err != nil {
			return err
		}
		_, err = w.Write(data)
		return err
	})
	if err != nil {
		_ = zw.Close()
		_ = f.Close()
		return err
	}
	if err := zw.Close(); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}
