#!/usr/bin/env sh
# Assemble the docc Cowork artifacts from the starter profile.
#
# Produces (all git-ignored — regenerate anytime):
#   1. docc/                                     — the generated skill directory
#   2. docc-cowork-skill.zip                     — standalone skill (Customize > Skills upload)
#   3. marketplace/plugins/docc/skills/docc/     — experimental plugin payload
#
# Everything derived from the profile — SKILL.md, config/, examples/ — is
# generated by `docc profile package`, so the skill's instructions cannot drift
# from the document types it actually ships. Only host-specific guidance is
# hand-written, in host-notes.md.
#
# Run from anywhere:  sh cowork/assemble.sh

set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)     # cowork/
ROOT=$(cd "$HERE/.." && pwd)                           # repo root
SKILL="$HERE/docc"
PROFILE="$ROOT/internal/starter/files/docc"
cd "$ROOT"

VER=$(git describe --tags --dirty --always 2>/dev/null || echo 0.0.0-dev)

# 1. The packaging tool, built for this machine so it can run here.
TOOLS=$(mktemp -d)
trap 'rm -rf "$TOOLS"' EXIT
echo "building the packaging tool ..."
go build -trimpath -o "$TOOLS/docc" ./cmd/docc

# 2. The bundled binary: x86_64 Linux, the Cowork VM's architecture.
echo "building docc ${VER}-cowork (linux/amd64) ..."
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath \
  -ldflags "-s -w -X main.buildVersion=${VER}-cowork" \
  -o "$TOOLS/docc-linux-amd64" ./cmd/docc

# 3. Generate the skill from the starter profile.
echo "packaging the skill ..."
rm -rf "$SKILL"
"$TOOLS/docc" profile package \
  --schema-dir "$PROFILE/schemas" \
  --theme-dir  "$PROFILE/themes" \
  --out        "$SKILL" \
  --name       docc \
  --with-binary "$TOOLS/docc-linux-amd64" \
  --notes      "$HERE/host-notes.md" \
  --zip        "$HERE/docc-cowork-skill.zip"

# 4. Plugin payload — mirror the skill into the plugin's skills/ tree.
echo "syncing plugin skill payload ..."
DEST="$HERE/marketplace/plugins/docc/skills/docc"
rm -rf "$DEST"
mkdir -p "$(dirname "$DEST")"
cp -r "$SKILL" "$DEST"

echo "done."
echo "  skill      : $SKILL"
echo "  standalone : $HERE/docc-cowork-skill.zip"
echo "  plugin     : $HERE/marketplace/  (experimental prototype only)"
